import 'package:flutter/material.dart';

Color primaryColor = Color(0xffffffff), accentColor = Colors.blueAccent;

List<Map<String, dynamic>> cgpaList = [
  {
    "year": 1,
    "semester": 1,
    "total_credit": 21.0,
  },
  {
    "year": 1,
    "semester": 2,
    "total_credit": 19.5,
  },
  {
    "year": 2,
    "semester": 1,
    "total_credit": 21.0,
  },
  {
    "year": 2,
    "semester": 2,
    "total_credit": 21.0,
  },
  {
    "year": 3,
    "semester": 1,
    "total_credit": 19.5,
  },
  {
    "year": 3,
    "semester": 2,
    "total_credit": 19.5,
  },
  {
    "year": 4,
    "semester": 1,
    "total_credit": 22.5,
  },
  {
    "year": 4,
    "semester": 2,
    "total_credit": 21.0,
  },
];

List<Map<String, dynamic>> courseList = [
  {
    "no": "CHEM 1107",
    "title": "Chemistry",
    "credit": 3,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "EEE 1101",
    "title": "Electrical Circuits I",
    "credit": 3,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "MATH 1103",
    "title": "Mathematics I",
    "credit": 3,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "ME 1101",
    "title": "Mechanical Engineering Fundamentals",
    "credit": 3,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "PHY 1105",
    "title": "Physics I",
    "credit": 3,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "CHEM 1108",
    "title": "Chemistry Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "EEE 1102",
    "title": "Electrical Circuits I Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "ME 1102",
    "title": "Mechanical Engineering Fundamentals Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "PHY 1106",
    "title": "Physics I Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 1,
  },
  {
    "no": "CE 1201",
    "title": "Mechanics of Materials",
    "credit": 3,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "EEE 1201",
    "title": "Electrical Circuits II",
    "credit": 3,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "MATH 1203",
    "title": "Mathematics II",
    "credit": 3,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "MATH 1213",
    "title": "Mathematics III",
    "credit": 3,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "PHY 1205",
    "title": "Physics II",
    "credit": 3,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "CE 1202",
    "title": "Engineering Drawing",
    "credit": 1.5,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "EEE 1202",
    "title": "Electrical Circutis II Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "EEE 1210",
    "title": "Elecrical Circuits Simulation Lab",
    "credit": 1.5,
    "year": 1,
    "semester": 2,
  },
  {
    "no": "EEE 2103",
    "title": "Electronics I",
    "credit": 3,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2105",
    "title": "Energy Conversion I",
    "credit": 3,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2109",
    "title": "Programming Language",
    "credit": 3,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "HUM 2109",
    "title": "English and Sociology",
    "credit": 3,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "MATH 2103",
    "title": "Mathematics IV",
    "credit": 3,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2104",
    "title": "Electronics I Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2106",
    "title": "Energy Conversion I Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2110",
    "title": "Programming Language Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "HUM 2110",
    "title": "Developing English Skills Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 1,
  },
  {
    "no": "EEE 2203",
    "title": "Electronics II",
    "credit": 3,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2205",
    "title": "Energy Conversion II",
    "credit": 3,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2211",
    "title": "Measurement and Instrumentation",
    "credit": 3,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "HUM 2209",
    "title": "Accounting and Economics",
    "credit": 3,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "MATH 2203",
    "title": "Mathematics V",
    "credit": 3,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2204",
    "title": "Electronics II Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2206",
    "title": "Energy Conversion II Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2210",
    "title": "Electronic Circuit Simulation Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 2212",
    "title": "Measurement and Instrumentation Lab",
    "credit": 1.5,
    "year": 2,
    "semester": 2,
  },
  {
    "no": "EEE 3103",
    "title": "Digital Electronics I",
    "credit": 3,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3107",
    "title": "Signals and Linear Systems",
    "credit": 3,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3113",
    "title": "Electrical Properties of Materials",
    "credit": 3,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3117",
    "title": "Electromagnetics",
    "credit": 3,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "HUM 3109",
    "title": "Industrial Management",
    "credit": 3,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3100",
    "title": "Electrical Service Design",
    "credit": 1.5,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3104",
    "title": "Digital Electronics I Lab",
    "credit": 1.5,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3110",
    "title": "Numerical Technique Lab",
    "credit": 1.5,
    "year": 3,
    "semester": 1,
  },
  {
    "no": "EEE 3203",
    "title": "Solid State Devices",
    "credit": 3,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3205",
    "title": "Power System I",
    "credit": 3,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3207",
    "title": "Communication Theory",
    "credit": 3,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3209",
    "title": "Microprocessor, Interfacing and System Design",
    "credit": 3,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3217",
    "title": "Digital Signal Processing I",
    "credit": 3,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3208",
    "title": "Communication Theory Lab",
    "credit": 1.5,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3210",
    "title": "Microprocessor, Interfacing and System Design Lab",
    "credit": 1.5,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 3218",
    "title": "Digital Signal Processing I Lab",
    "credit": 1.5,
    "year": 3,
    "semester": 2,
  },
  {
    "no": "EEE 4105",
    "title": "Control System I",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective I (EEE 4137/EEE 4153/EEE 4177)",
    "title":
        "Digital Electronics II/Power System II/Random Signals and Processes",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective II (EEE 4133/EEE 4157/EEE 4173/EEE 4193)",
    "title":
        "VLSI I/High Voltage Engineering/Microwave Engineering/Microcontroller based System Design",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective III (EEE 4131/EEE 4151/EEE 4171)",
    "title":
        "Processing and Fabrication Technology/Energy Conversion III/Digital Signal Processing II",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective IV (EEE 4135/EEE 4155/EEE 4175/EEE 4195)",
    "title":
        "Analog Integrated Circuit/Power Plant Engineering and Economy/Optical Fiber Communication/Real Time Computer System",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "EEE 4100",
    "title": "Project and Thesis",
    "credit": 3,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "EEE 4106",
    "title": "Control System I Lab",
    "credit": 1.5,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective I Lab (EEE 4138/EEE 4154/EEE 4178)",
    "title":
        "Digital Electronics II Lab/Power System II Lab/Random Signals and Processes Lab",
    "credit": 1.5,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "Elective II Lab (EEE 4134/EEE 4158/EEE 4174/EEE 4194)",
    "title":
        "VLSI I Lab/High Voltage Engineering Lab/Microwave Engineering Lab/Microcontroller based System Design Lab",
    "credit": 1.5,
    "year": 4,
    "semester": 1,
  },
  {
    "no": "HUM 4229",
    "title": "Society, Ethics and Technology",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective V (EEE 4233/EEE 4253/EEE 4273/CSE 4293)",
    "title":
        "Optoelectronics/Power System Reliability/Mobile Cellular Communication/Computer Architecture",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective VI (EEE 4231/EEE 4237/EEE 4251/EEE 4271/CSE 4291)",
    "title":
        "VLSI II/Biomedical Instrumentation/Power System Protection/Digital Communication/Computer Networks",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective VII (EEE 4235/EEE 4239/EEE 4255/EEE 4275/CSE 4295)",
    "title":
        "Compound Semiconductor and Hetero-Junction Devices/Semiconductor Device Theory/Power System Operation and Control/Telecommunication Engineering/Multimedia Communications",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective VIII (EEE 4221/EEE 4227/EEE 4225)",
    "title":
        "Control System II/Power Electronics/Numerical Methods for Engineering",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "EEE 4200",
    "title": "Project and Thesis",
    "credit": 3,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective VI Lab (EEE 4232/EEE 4238/EEE 4252/EEE 4272/CSE 4292)",
    "title":
        "VLSI II Lab/Biomedical Instrumentation Lab/Power System Protection Lab/Digital Communication Lab/Computer Networks Lab",
    "credit": 1.5,
    "year": 4,
    "semester": 2,
  },
  {
    "no": "Elective VIII Lab (EEE 4222/EEE 4228/EEE 4226)",
    "title":
        "Control System II Lab/Power Electronics Lab/Numerical Methods for Engineering Lab",
    "credit": 1.5,
    "year": 4,
    "semester": 2,
  },
];
